baseURL = 'https://www.julien-maxant.com/'
locale = 'fr-fr'
title = 'Julien Maxant'
copyright = '2026 - Julien Maxant'
defaultContentLanguage = 'fr'
defaultContentLanguageInSubdir = false
removePathAccents = true

[params]
madeWith = 'Made with Hugo & based on bear-cub theme'
baseline = 'Développement web'

[params.author]
name = 'Julien Maxant'

[taxonomies]
tag = 'tags'

[module]
[[module.imports]]
path = 'github.com/clente/hugo-bearcub'
